name: ${name}
version: ${version}
main: ${groupId}.${artifactId}.${name}Plugin
author: ${author}
commands:
    survivalgames:
        description: Base command
        usage: /<command> [args]
        aliases: [sg]
permissions:
    survivalgames.command:
        description: Base permission
        default: true
    survivalgames.create:
        description: Allows /sg create
        default: op
    survivalgames.delete:
        description: Allows /sg delete
        default: op
    survivalgames.list:
        description: Allows /sg list
        default: true